### ISSUE TITLE
Who maintains this project?

### ISSUE THREAD

**Issue by riemann89** [darka91/ScientificComputing#1]
:D

**Comment by mello29** [comment]
According to the rumors, the creator and main contributor @darka91 is currently busy studying Finite Fields.

**Comment by CharlieTrip** [comment]
> According to the rumors, the creator and main contributor @darka91 is currently busy studying Finite Fields.

Uooo... that's amazing!

**Comment by riemann89** [comment]
Perfect, thanks! I close the issue.
